version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: myapp-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: myapp-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  db:
    image: postgres:16
    container_name: myapp-db
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./exports:/tmp           # <--- Added this line to map ./exports folder to /tmp inside container
    ports:
      - "5432:5432"

volumes:
  pgdata:
